FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
  openssl \
  sudo \
  ca-certificates \
  sqlite3 \
  wget

RUN wget https://download.racket-lang.org/installers/8.9/racket-8.9-x86_64-linux-cs.sh && chmod 755 ./racket-8.9-x86_64-linux-cs.sh && \
    ./racket-8.9-x86_64-linux-cs.sh --unix-style && \
    raco pkg install --auto pollen hyphenate xexpr-path
